### ISSUE TITLE
Bổ sung "số trường hợp đã được cứu hộ" trong phần thống kê 

### ISSUE THREAD

**Issue by hailoc12** [hailoc12/cuuhomientrung#11]
Bổ sung thêm cột "số trường hợp được cứu hộ" vào các bảng thống kê (tỉnh, huyện, xã) để có metric đo lường hiệu quả hoạt động của dự án 
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/288295/96541027-52189000-12c9-11eb-8575-3da72da574d9.png">

**Comment by khiem111189** [comment]
Nếu thuận tiện, mình có thể thêm vào chức năng sắp xếp thứ tự theo các cột như cột "Hộ dân cần ứng cứu" để biết những khu vực cần ưu tiên. Xin cảm ơn!

**Comment by khiem111189** [comment]
Bên cạnh đó, mình có thể thêm một mục cho phép mọi người chia sẻ những khu vực an toàn, có thực phẩm để các đội cứu hộ có thể đưa người dân tới.
