### ISSUE TITLE
Lỗi lặp thông tin Đơn vị hành chính

### ISSUE THREAD

**Issue by trailaptrinh** [hailoc12/cuuhomientrung#37]
Danh sách đơn vị hành chính cấp Huyện, Xã bị trùng lặp rất nhiều, cần kiểm tra trùng tên trong cùng 1 cấp cha. Ví dụ trong Quảng Bình thì ko thể có 2 Huyện là Lệ Thủy...
Lỗi lặp với tất cả các cấp
![image](https://user-images.githubusercontent.com/28603856/96616024-3f837280-132c-11eb-9014-e051ca01c2c9.png)

**Comment by freeloneman** [comment]
Các bạn dev xem lấy API này để chuẩn hóa database nhé
https://thongtindoanhnghiep.co/rest-api

**Comment by trailaptrinh** [comment]
Dữ liệu về tt Địa chính nó phân cấp thế này: Tỉnh/TP, Quận/Huyện/Thị xã/Thị trấn Phường/Xã, Thôn/Xóm/Khu Phố

**Comment by dieudv** [comment]
Thêm option unique=True vào trường name để tránh trùng lặp, nhưng cần gộp data lặp đi đã.

**Comment by hailoc12** [comment]
Em đã viết script để merge data, hiện tại đang bổ sung đầy đủ danh sách huyện, xã lên để các bạn tnv không ấn tạo mới

**Comment by hailoc12** [comment]
Dữ liệu Đơn vị hành chính đã được merge và add đầy đủ các đơn vị hành chính dựa trên data từ https://thongtindoanhnghiep.co/rest-api

**Comment by dieudv** [comment]
Không có data cấp thôn xóm nhỉ
