### ISSUE TITLE
Không chọn được đơn vị Cấp Huyện khi thêm mới Hộ dân

### ISSUE THREAD

**Issue by trailaptrinh** [hailoc12/cuuhomientrung#43]
Sau khi chọn tỉnh, combo Huyện không có dữ liệu
![image](https://user-images.githubusercontent.com/28603856/96619381-4d3af700-1330-11eb-9e9c-d6c0e5102210.png)

**Comment by hailoc12** [comment]
Đã fix bạn nhé
