### ISSUE TITLE
Thêm lọc đội cứu hộ theo "số điện thoại"

### ISSUE THREAD

**Issue by dothanhlam97** [hailoc12/cuuhomientrung#9]
Reprod: https://cuuhomientrung.info/app/cuuho/
<img width="845" alt="Screenshot 2020-10-20 at 05 00 32" src="https://user-images.githubusercontent.com/17758870/96538776-414c2800-1291-11eb-9dd7-476f6702b998.png">

**Comment by dothanhlam97** [comment]
https://github.com/hailoc12/cuuhomientrung/pull/14/

**Comment by hailoc12** [comment]
Phần lọc này thì không hợp lý lắm nhỉ (vì có rất nhiều số). Hiện tại đội cứu hộ có thể tìm kiếm thông qua số điện thoại
